### ISSUE TITLE
Migrate Component from VSHN internal GitLab

### ISSUE THREAD

**Issue by tobru** [projectsyn/component-steward#1]
Migrate the component from the VSHN internal GitLab to GitHub and add tags to the repository once migrated. Also check and add the license to the repository.

**Comment by srueg** [comment]
Final migration can only happen once https://github.com/projectsyn/commodore/issues/73 is implemented.

**Comment by srueg** [comment]
https://github.com/projectsyn/component-steward/pull/2

**Comment by srueg** [comment]
Archived the git repo on git.vshn.net and configured Commodore global repo to use GitHub
