### ISSUE TITLE
Configure resource requests and limits

### ISSUE THREAD

**Issue by anothertobi** [projectsyn/component-steward#23]
## Context
Steward should configure default requests and limits to have a better QoS class than BestEffort. On some clusters there are default resource requests and limits (usually 250/250), which Steward doesn't consume.

Same as https://github.com/projectsyn/component-argocd/issues/41

## Alternatives
n/a

**Comment by simu** [comment]
> Steward should configure default requests and limits to have a better QoS class than BestEffort.

We already set requests and limits in https://github.com/projectsyn/component-steward/blob/1d84659dc3c7d18e566944ac08c59f284d0c3024/component/main.jsonnet#L54-L57

Therefore, the Steward pod should run with QoS class `Burstable` according to the Kubernetes docs: https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

I don't think it's necessary to have Steward running with QoS class `Guaranteed` by default.

I will create a PR which allows users to customize the resource requests and limits of Steward through the hierarchy.
